packages:
  - docs
  - packages-plugins/*
  - packages-presets/*
  - packages-themes/*
  - packages/*

overrides:
  monaco-editor>dompurify: 3.4.12

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAge: 0

storeDir: /tmp/pnpm-store2
