/**
 * TypeScript type declarations fed to Monaco's TypeScript worker so that
 * `import { … } from 'docx-kit'` and `import { … } from 'docx'` resolve
 * without diagnostics errors.
 */
export const DOCX_KIT_TYPES = [
  "declare module 'docx-kit' {",
  '  export class DocxBuilder<TStyles = any, TPlugins = any> {',
  '    constructor(config?: DocxKitConfig)',
  '    h1(text: string, options?: Partial<HeadingOptions>): this',
  '    h2(text: string, options?: Partial<HeadingOptions>): this',
  '    h3(text: string, options?: Partial<HeadingOptions>): this',
  '    h4(text: string, options?: Partial<HeadingOptions>): this',
  '    h5(text: string, options?: Partial<HeadingOptions>): this',
  '    h6(text: string, options?: Partial<HeadingOptions>): this',
  '    // Overload 1: plain text paragraph',
  '    p(text: string, options?: Partial<ParagraphOptions>): this',
  '    // Overload 2: rich content (children array)',
  '    p(children: (TextNode | ImageNode)[], options?: Partial<ParagraphOptions>): this',
  '    bulletList(items: (string | { text: string; className?: string; style?: any })[], options?: { bullet?: string; level?: number; className?: string; style?: any }): this',
  '    numberedList(items: (string | { text: string; className?: string; style?: any })[], options?: { numberingFormat?: string; start?: number; level?: number; className?: string; style?: any }): this',
  '    hyperlink(url: string, text: string, options?: { className?: string; style?: any }): this',
  '    table<TData extends Record<string, unknown>>(options: TableOptions<TData>): this',
  '    image(options: { data: Uint8Array | string; width?: number; height?: number; alt?: string; floating?: boolean | { x?: number; y?: number } }): this',
  '    pageBreak(): this',
  '    section(config?: SectionConfig): this',
  '    plugin<TName extends string & keyof TPlugins>(name: TName, options: TPlugins[TName], style?: any): this',
  '    use<TName extends string, TOptions>(plugin: DocxPlugin<TName, TOptions>): DocxBuilder<TStyles, TPlugins & Record<TName, TOptions>>',
  '    add(node: any): this',
  '    span(text: string, style?: any): TextNode',
  '    inlineImg(options: { data: Uint8Array | string; width?: number; height?: number; alt?: string }): ImageNode',
  '    toBlob(): Promise<Blob>',
  '    toUint8Array(): Promise<Uint8Array>',
  '    toBuffer(): Promise<Uint8Array>',
  '    toBase64(): Promise<string>',
  '    save(filename: string): Promise<void>',
  '    toJSON(): object',
  '  }',
  '',
  '  interface TextNode { type: "text"; text: string; style?: any }',
  '  interface ImageNode { type: "image"; data: Uint8Array | string; width?: number; height?: number; alt?: string }',
  '',
  '  interface DocxKitConfig {',
  '    page?: PageConfig',
  '    styles?: any',
  '    defaults?: {',
  '      cell?: any',
  '      image?: any',
  '      paragraph?: any',
  '      table?: any',
  '      text?: any',
  '    }',
  '    metadata?: {',
  '      title?: string',
  '      subject?: string',
  '      creator?: string',
  '      description?: string',
  '      keywords?: string[]',
  '      lastModifiedBy?: string',
  '    }',
  '  }',
  '',
  '  interface PageConfig {',
  '    size?: "A3" | "A4" | "Legal" | "Letter" | { width: number; height: number }',
  '    orientation?: "portrait" | "landscape"',
  '    margin?: number | string | { top?: number; right?: number; bottom?: number; left?: number }',
  '  }',
  '',
  '  interface SectionConfig {',
  '    page?: PageConfig',
  '    header?: HeaderFooterConfig',
  '    footer?: HeaderFooterConfig',
  '  }',
  '',
  '  interface HeaderFooterConfig {',
  '    default?: HeaderFooterContent',
  '    first?: HeaderFooterContent',
  '    even?: HeaderFooterContent',
  '  }',
  '',
  '  interface HeaderFooterContent {',
  '    children: string[]',
  '  }',
  '',
  '  interface HeadingOptions {',
  '    className?: string',
  '    id?: string',
  '    style?: any',
  '  }',
  '',
  '  interface ParagraphOptions {',
  '    className?: string',
  '    id?: string',
  '    style?: any',
  '  }',
  '',
  '  interface TableColumn {',
  '    key: string',
  '    title: string',
  '    width?: string',
  '    colSpan?: number',
  '    align?: "left" | "center" | "right"',
  '    render?: (value: any, row: any, index: number) => string',
  '  }',
  '',
  '  interface TableOptions<TData> {',
  '    columns: TableColumn[]',
  '    data: TData[]',
  '    bordered?: boolean',
  '    header?: boolean',
  '    striped?: boolean',
  '    cellStyle?: any',
  '    headerCellStyle?: any',
  '  }',
  '',
  '  interface DocxPlugin<TName extends string = string, TOptions = unknown> {',
  '    name: TName',
  '    setup?: () => void | Promise<void>',
  '    render: (options: TOptions, context: PluginRenderContext) => unknown | Promise<unknown>',
  '  }',
  '',
  '  interface PluginRenderContext {',
  '    config: DocxKitConfig',
  '    compileNode: (node: any) => Promise<unknown>',
  '    utils: { image: { fromBlob: (b: Blob) => Promise<Uint8Array>; fromDataUrl: (url: string) => Uint8Array | Promise<Uint8Array> } }',
  '  }',
  '',
  '  export function definePlugin<const TName extends string, TOptions>(plugin: DocxPlugin<TName, TOptions>): DocxPlugin<TName, TOptions>',
  '  export function defineStyles(styles: Record<string, any>): Record<string, any>',
  '  export function createDocx(config?: DocxKitConfig): DocxBuilder',
  '  export function renderDocx(doc: DocxBuilder): Promise<Uint8Array>',
  '',
  '  // -- Standalone inline helpers ----------------------------------------',
  '  export function span(text: string, style?: any): TextNode',
  '  export function inlineImg(options: { data: Uint8Array | string; width?: number; height?: number; alt?: string }): ImageNode',
  '',
  '  // -- Built-in plugins (factory functions) -----------------------------',
  '  export function calloutPlugin(): DocxPlugin<"callout", any>',
  '  export function codeBlockPlugin(): DocxPlugin<"codeBlock", any>',
  '  export function coverPagePlugin(): DocxPlugin<"coverPage", any>',
  '  export function dataTablePlugin(): DocxPlugin<"dataTable", any>',
  '  export function echartsPlugin(): DocxPlugin<"echarts", any>',
  '  export function meetingMinutesPlugin(): DocxPlugin<"meetingMinutes", any>',
  '  export function pageNumberPlugin(): DocxPlugin<"pageNumber", any>',
  '  export function propertyTablePlugin(): DocxPlugin<"propertyTable", any>',
  '  export function qrcodePlugin(): DocxPlugin<"qrcode", any>',
  '  export function signatureBlockPlugin(): DocxPlugin<"signatureBlock", any>',
  '  export function timelinePlugin(): DocxPlugin<"timeline", any>',
  '  export function watermarkPlugin(): DocxPlugin<"watermark", any>',
  '',
  '  // -- Theme helpers ----------------------------------------------------',
  '  export function useTheme(id: string): any',
  '  export const THEME_LIST: any[]',
  '',
  '  interface DocxPreset {',
  '    readonly id: string',
  '    readonly name: string',
  '    readonly description: string',
  '    readonly config: DocxKitConfig',
  '  }',
  '',
  '  export const classicPreset: DocxPreset',
  '  export const modernPreset: DocxPreset',
  '  export const academicPreset: DocxPreset',
  '  export const PRESET_LIST: DocxPreset[]',
  '  export function usePreset(id: string): DocxPreset | undefined',
  '}',
  '',
  "declare module 'docx' {",
  '  export class Paragraph {',
  '    constructor(options?: {',
  '      text?: string',
  '      children?: any[]',
  '      heading?: any',
  '      alignment?: any',
  '      spacing?: { before?: number; after?: number; line?: number }',
  '      indent?: { left?: number; right?: number; firstLine?: number }',
  '      border?: { top?: any; bottom?: any; left?: any; right?: any }',
  '      bold?: boolean',
  '      italics?: boolean',
  '      numbering?: { reference: string; level: number }',
  '    })',
  '  }',
  '  export class TextRun {',
  '    constructor(options?: { text?: string; bold?: boolean; italics?: boolean; color?: string; size?: number; font?: string; superScript?: boolean; subScript?: boolean; highlight?: string })',
  '  }',
  '  export class Table {',
  '    constructor(options: { rows: TableRow[]; width?: { size: number; type: any } })',
  '  }',
  '  export class TableRow {',
  '    constructor(options: { children: TableCell[]; tableHeader?: boolean })',
  '  }',
  '  export class TableCell {',
  '    constructor(options: { children: Paragraph[]; width?: any; columnSpan?: number; shading?: any })',
  '  }',
  '  export class ImageRun {',
  '    constructor(options: { data: Uint8Array | string; transformation: { width: number; height: number }; type?: string })',
  '  }',
  '  export class PageBreak {}',
  '  export class ExternalHyperlink {',
  '    constructor(options: { children: any[]; link: string })',
  '  }',
  '  export const AlignmentType: { LEFT: any; CENTER: any; RIGHT: any; JUSTIFIED: any }',
  '  export const BorderStyle: { SINGLE: any; DASHED: any; DOTTED: any; DOUBLE: any }',
  '  export const HeadingLevel: { HEADING_1: any; HEADING_2: any; HEADING_3: any; HEADING_4: any; HEADING_5: any; HEADING_6: any }',
  '  export const WidthType: { PERCENTAGE: any; AUTO: any }',
  '  export const LevelFormat: { DECIMAL: any; UPPER_ROMAN: any; LOWER_ROMAN: any; UPPER_LETTER: any; LOWER_LETTER: any }',
  '  export class Document {',
  '    constructor(options: any)',
  '  }',
  '  export class Packer {',
  '    static toBlob(doc: Document): Promise<Blob>',
  '    static toBuffer(doc: Document): Promise<Uint8Array>',
  '    static toBase64String(doc: Document): Promise<string>',
  '  }',
  '  export class Header {',
  '    constructor(options: { children: Paragraph[] })',
  '  }',
  '  export class Footer {',
  '    constructor(options: { children: Paragraph[] })',
  '  }',
  '}',
].join('\n')
