/**
 * Generate Monaco-friendly type declarations for the playground.
 *
 * Reads the real `.d.ts` files emitted by `tsdown` and produces
 * a TypeScript file that exports `DOCX_KIT_TYPES` — a string constant
 * containing `declare module` blocks that Monaco's TypeScript worker
 * can consume.
 *
 * Strategy (avoiding diamond-dependency duplication):
 *   1. Read the umbrella's `dist/browser.d.ts` first. It contains the
 *      `useTheme`, `usePreset`, `BUILTIN_THEMES`, `PRESET_LIST`,
 *      `normalizeImageData`, `createDocxPreview` and all the
 *      re-exported *types* (`export * from "@docxkit/core"`) that
 *      `docx-kit` exposes as a public API.
 *   2. For every leaf workspace package (plugins, presets, themes,
 *      loader, renderer, …), read its `dist/index.d.ts` and append
 *      any declaration whose name has *not* been seen before. This
 *      deduplicates the `export *` re-exports vs. the actual leaf
 *      declarations, and avoids repeating the same `DocxTheme` /
 *      `DocxPreset` interfaces three times across theme/preset
 *      packages.
 *   3. Concatenate everything into `declare module 'docx-kit' { … }`.
 *   4. Separately, read `node_modules/docx/dist/index.d.ts` and apply
 *      the same transformation for `declare module 'docx' { … }`.
 *
 * The resulting blocks are wrapped in a template literal assigned to
 * `DOCX_KIT_TYPES`, using `unindent` from `@ntnyq/utils` for readability.
 *
 * @example
 *   pnpm tsx scripts/generate-monaco-types.ts
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')

// ─── Configuration ────────────────────────────────────────────────

/**
 * The umbrella package — its `browser.d.ts` contains the *unique*
 * value exports (`useTheme`, `usePreset`, `BUILTIN_THEMES`, …) plus
 * `export * from "@docxkit/core"`. Processing this first guarantees
 * those names are recorded as "seen" before the leaf packages can
 * re-introduce them.
 */
const UMBRELLA_DTS = 'packages/docx-kit/dist/browser.d.ts'

/**
 * Leaf workspace packages whose types are not fully re-exported by
 * the umbrella, or whose unique types we'd like to make available
 * in the playground (in case a user wants to import them via the
 * deep package path rather than `docx-kit`).
 */
const DOCXKIT_LEAF_PACKAGES = [
  // Core (types are mostly re-exported by umbrella, but include
  // here for completeness — dedup will drop the duplicates).
  'packages/core/dist/index.d.ts',
  // Plugins.
  'packages-plugins/callout/dist/index.d.ts',
  'packages-plugins/code-block/dist/index.d.ts',
  'packages-plugins/cover-page/dist/index.d.ts',
  'packages-plugins/data-table/dist/index.d.ts',
  'packages-plugins/echarts/dist/index.d.ts',
  'packages-plugins/meeting-minutes/dist/index.d.ts',
  'packages-plugins/page-number/dist/index.d.ts',
  'packages-plugins/property-table/dist/index.d.ts',
  'packages-plugins/qrcode/dist/index.d.ts',
  'packages-plugins/signature-block/dist/index.d.ts',
  'packages-plugins/timeline/dist/index.d.ts',
  'packages-plugins/watermark/dist/index.d.ts',
  // Presets.
  'packages-presets/academic/dist/index.d.ts',
  'packages-presets/classic/dist/index.d.ts',
  'packages-presets/modern/dist/index.d.ts',
  // Themes.
  'packages-themes/minimal/dist/index.d.ts',
  'packages-themes/ocean/dist/index.d.ts',
  'packages-themes/warm/dist/index.d.ts',
  // Infrastructure.
  'packages/loader/dist/index.d.ts',
  'packages/renderer/dist/index.d.ts',
]

const DOCX_DTS = resolve(
  ROOT,
  'node_modules/.pnpm/docx@9.7.1/node_modules/docx/dist/index.d.ts',
)
/**
 * Mapping of plugin name (as registered via `.use()` / `.plugin()`) to the
 * name of the option-type interface exported by that plugin's `.d.ts`.
 *
 * Used to emit a `BuiltinPluginMap` augmentation so the playground
 * gets type-safe `.plugin('callout', { ... })` calls without
 * requiring an explicit `.use()` chain.
 */
const PLUGIN_NAME_TO_OPTIONS_TYPE: Record<string, string> = {
  callout: 'CalloutOptions',
  codeBlock: 'CodeBlockOptions',
  coverPage: 'CoverPageOptions',
  dataTable: 'DataTableOptions',
  echarts: 'EChartsPluginOptions',
  meetingMinutes: 'MeetingMinutesOptions',
  pageNumber: 'PageNumberOptions',
  propertyTable: 'PropertyTableOptions',
  qrcode: 'QRCodePluginOptions',
  signatureBlock: 'SignatureBlockOptions',
  timeline: 'TimelineOptions',
  watermark: 'WatermarkOptions',
}

const OUTPUT = resolve(ROOT, 'docs/.vitepress/utils/monacoTypes.generated.ts')

// ─── Header (emitted verbatim at the top of the generated file) ───
const HEADER = [
  '/**',
  ' * AUTO-GENERATED by `scripts/generate-monaco-types.ts` — DO NOT EDIT.',
  ' *',
  ' * Source of truth: the `.d.ts` files listed in',
  ' * `DOCXKIT_LEAF_PACKAGES` (see the generator script).',
  ' *',
  ' * To regenerate, run `pnpm tsx scripts/generate-monaco-types.ts`',
  ' * (also runs automatically as part of `pnpm docs:build`).',
  ' */',
  '',
]

// ─── Regex patterns (hoisted to avoid the "used before defined" lint rule) ─
const IMPORT_LINE_PATTERN = /^import\s/

// Matches `export { … };` (or `export {}`) at end of line, allowing optional
// whitespace and trailing semicolon. Bounded by the absence of further `{`.
const EXPORT_LIST_PATTERN = /^export\s*\{[^}]*\};?\s*$/

// Captures leading whitespace before `export` and consumes the `export` keyword
// (and one trailing space) when followed by a declaration-style identifier.
const EXPORT_PREFIX_PATTERN =
  /^(\s*)export\s+(?=declare\b|type\b|interface\b|class\b|function\b|const\b|enum\b|namespace\b|abstract\b|async\b)/

// Matches a top-level declaration. We use this to extract the declared
// name(s) so the dedup step can skip leaves that have already contributed
// a name to the ambient module.
//
// Captures:
//   1. leading indentation
//   2. kind keyword (declare / type / interface / …)
//   3. the declared name (function/const/type/interface/enum/namespace/class)
//   4. for `export type { Foo, Bar }` (re-export forms) — comma-separated
//      list of names; not currently used because we strip the export list
const DECL_HEADER_PATTERN =
  /^(\s*)(?:export\s+)?(declare\s+)?(type|interface|class|function|const|enum|namespace|abstract\s+class|async\s+function)\s+([A-Za-z_$][\w$]*)/

// Captures the identifier names from a `export type { A, B as C }` form.
// Not currently used by the transformer (we strip export lists outright)
// but kept here for future extension.
const EXPORT_NAMED_LIST_PATTERN = /^export\s+(?:type\s+)?\{([^}]+)\};?\s*$/

/**
 * Build the `BuiltinPluginMap` interface that augments
 * `declare module 'docx-kit' { … }` so that `.plugin('callout', { … })`
 * (etc.) are type-safe without an explicit `.use()` chain.
 *
 * The block is appended to the `'docx-kit'` ambient module as a
 * nested `interface BuiltinPluginMap` (matching the runtime augmentation
 * done in `packages/docx-kit/src/types/plugin-map.ts`).
 */
function buildBuiltinPluginMapBlock(): string {
  const entries = Object.entries(PLUGIN_NAME_TO_OPTIONS_TYPE)
    .map(([pluginName, optionsType]) => `  ${pluginName}: ${optionsType}`)
    .join('\n')

  return [
    "declare module 'docx-kit' {",
    '  interface BuiltinPluginMap {',
    entries,
    '  }',
    '}',
  ].join('\n')
}

// ─── Build `declare module 'docx' { … }` ────────────────────────
function buildDocxBlock(): string {
  if (!existsSync(DOCX_DTS)) {
    throw new Error(
      `[generate-monaco-types] missing ${DOCX_DTS}\n`
        + `Run \`pnpm install\` first.`,
    )
  }

  const seenNames = new Set<string>()
  const body = transformLeafDts(readFileSync(DOCX_DTS, 'utf8'), seenNames)

  return [`declare module 'docx' {`, indent(body, 2), '}'].join('\n')
}

// ─── Build `declare module 'docx-kit' { … }` ─────────────────────
function buildDocxKitBlock(): string {
  const seenNames = new Set<string>()
  const parts: string[] = []

  // 1. Process the umbrella first so its unique value exports
  //    (useTheme, usePreset, BUILTIN_THEMES, …) win the dedup race.
  const umbrellaBody = readAndTransform(UMBRELLA_DTS, seenNames)
  if (umbrellaBody) {
    parts.push(umbrellaBody)
  }

  // 2. Walk the leaf packages, appending only declarations that
  //    haven't been seen yet.
  for (const relPath of DOCXKIT_LEAF_PACKAGES) {
    const body = readAndTransform(relPath, seenNames)
    if (body) {
      parts.push(body)
    }
  }

  return [
    `declare module 'docx-kit' {`,
    indent(parts.join('\n\n'), 2),
    '}',
  ].join('\n')
}

/**
 * Extract the top-level declaration name from a `declare …` / `type …` /
 * `interface …` line, e.g.
 *
 *   - `declare function useTheme(id: string): DocxTheme | undefined;`
 *     → `"useTheme"`
 *   - `type DocxTheme = { … }`
 *     → `"DocxTheme"`
 *   - `export type { Foo, Bar }`
 *     → `["Foo", "Bar"]`
 *   - `   interface HeadingNode { … }`
 *     → `"HeadingNode"`
 *
 * Returns `null` when the line is not a recognisable declaration header.
 */
function extractDeclaredNames(line: string): string[] | null {
  const trimmed = line.trim()

  // `export type { Foo, Bar }` (re-export list of types)
  const named = trimmed.match(EXPORT_NAMED_LIST_PATTERN)
  if (named) {
    return named[1]
      .split(',')
      .map(part =>
        part
          .trim()
          .split(/\s+as\s+/)
          .pop()!
          .trim(),
      )
      .filter(Boolean)
  }

  const m = trimmed.match(DECL_HEADER_PATTERN)
  if (!m) {
    return null
  }
  return [m[4]]
}

// ─── Helpers ────────────────────────────────────────────────────────
/** Indent every non-empty line of `text` by `n` spaces. */
function indent(text: string, n: number): string {
  const pad = ' '.repeat(n)
  return text
    .split('\n')
    .map(line => (line.length === 0 ? line : pad + line))
    .join('\n')
}

function main() {
  const docxkitBlock = buildDocxKitBlock()
  const docxBlock = buildDocxBlock()
  const builtinPluginMapBlock = buildBuiltinPluginMapBlock()

  const content = [docxkitBlock, '', docxBlock, '', builtinPluginMapBlock].join(
    '\n',
  )

  // Escape for template literal:
  //   1. \\  → \\\\   (literal backslash in the content)
  //   2. `   → \`    (backtick in the content)
  //   3. ${  → \${   (template literal type → interpolation in JS)
  const escaped = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')

  const output = [
    ...HEADER,
    '',
    "import { unindent } from '@ntnyq/utils'",
    '',
    'export const DOCX_KIT_TYPES = unindent(`',
    escaped,
    '`)',
    '',
  ].join('\n')

  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, output, 'utf8')

  console.log(`[generate-monaco-types] wrote ${OUTPUT}`)
  console.log(
    `[generate-monaco-types] ${output.length} bytes, ${output.split('\n').length} lines`,
  )
}

/**
 * Read a `.d.ts` file, transform it, and return its body fragment.
 * Missing files produce a warning and an empty string (build resilience).
 */
function readAndTransform(relPath: string, seenNames: Set<string>): string {
  const absPath = resolve(ROOT, relPath)
  if (!existsSync(absPath)) {
    console.warn(`[generate-monaco-types] skipping missing ${relPath}`)
    return ''
  }
  const source = readFileSync(absPath, 'utf8')
  return transformLeafDts(source, seenNames)
}

/**
 * Transform a single leaf package's `.d.ts` into an ambient-module
 * body fragment:
 *
 *   1. Strip every top-level `import … from "…"` line.
 *   2. Strip the trailing `export { … }` (and `export { }`) line.
 *   3. Strip the `export` keyword from `export declare …` / `export type …` / …
 *   4. Skip any declaration whose name is already in `seenNames`.
 *   5. Keep all `declare class/function/const/…` and `interface` / `type` lines.
 */
function transformLeafDts(source: string, seenNames: Set<string>): string {
  const lines = source.split('\n')
  const out: string[] = []
  let currentBlock: { lines: string[]; names: string[] } | null = null

  const flushBlock = (): void => {
    if (!currentBlock) {
      return
    }
    const allSeen = currentBlock.names.every(name => seenNames.has(name))
    if (!allSeen) {
      for (const name of currentBlock.names) {
        seenNames.add(name)
      }
      out.push(...currentBlock.lines)
    }
    currentBlock = null
  }

  for (const line of lines) {
    const trimmed = line.trim()

    // Skip `import … from "…"`.
    if (IMPORT_LINE_PATTERN.test(trimmed)) {
      continue
    }

    // Skip the trailing `export { … }` list.
    if (EXPORT_LIST_PATTERN.test(trimmed)) {
      continue
    }

    // Strip leading `export ` from `export declare …`.
    const cleaned = line.replace(EXPORT_PREFIX_PATTERN, '$1')

    // Top-level declaration header? Start (or extend) a new block.
    const isHeader =
      /^\s*(?:declare\s+|type\s+|interface\s+|class\s+|function\s+|const\s+|enum\s+|namespace\s+|abstract\s+class\s+|async\s+function\s+|export\s+(?:declare|type|interface|class|function|const|enum|namespace|abstract\s+class|async\s+function))/.test(
        cleaned,
      )
    const names = isHeader ? extractDeclaredNames(cleaned) : null

    if (names) {
      // Close the previous block (if any) before starting a new one.
      flushBlock()
      currentBlock = { lines: [cleaned], names }
    } else if (currentBlock) {
      currentBlock.lines.push(cleaned)
    } else {
      // Stray line (e.g. an orphan `}` or comment outside a declaration).
      // Drop it to keep the ambient module body clean.
    }
  }

  // Flush the last block.
  flushBlock()

  return out.join('\n')
}

// ─── CLI entry ─────────────────────────────────────────────────────
main()
