/**
 * Generate Monaco type libraries for the documentation playground.
 *
 * Each real declaration file is mounted at the same logical path it would
 * have under `node_modules`. This preserves imports, re-exports, aliases,
 * module augmentation, overloads, and generic function declarations.
 *
 * @example
 *   pnpm tsx scripts/generate-monaco-types.ts
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, relative, resolve, sep } from 'node:path'

interface TypeLibSource {
  sourcePath: string
  virtualPath: string
}

const ROOT = resolve(import.meta.dirname, '..')

const OUTPUT = resolve(ROOT, 'docs/.vitepress/utils/monacoTypes.generated.ts')

const HEADER = [
  '/**',
  ' * AUTO-GENERATED by `scripts/generate-monaco-types.ts` — DO NOT EDIT.',
  ' *',
  ' * Each entry mirrors a real declaration file at its logical node_modules',
  ' * path so Monaco resolves the same public API as TypeScript.',
  ' *',
  ' * To regenerate, run `pnpm tsx scripts/generate-monaco-types.ts`',
  ' * (also runs automatically as part of `pnpm docs:build`).',
  ' */',
  '',
]

const WORKSPACE_MODULES = [
  ['docx-kit', 'packages/docx-kit/dist/browser.d.ts'],
  ['@docxkit/core', 'packages/core/dist/index.d.ts'],
  ['@docxkit/plugin-badge', 'packages-plugins/badge/dist/index.d.ts'],
  ['@docxkit/plugin-barcode', 'packages-plugins/barcode/dist/index.d.ts'],
  ['@docxkit/plugin-callout', 'packages-plugins/callout/dist/index.d.ts'],
  ['@docxkit/plugin-changelog', 'packages-plugins/changelog/dist/index.d.ts'],
  ['@docxkit/plugin-code-block', 'packages-plugins/code-block/dist/index.d.ts'],
  ['@docxkit/plugin-cover-page', 'packages-plugins/cover-page/dist/index.d.ts'],
  ['@docxkit/plugin-data-table', 'packages-plugins/data-table/dist/index.d.ts'],
  ['@docxkit/plugin-divider', 'packages-plugins/divider/dist/index.d.ts'],
  ['@docxkit/plugin-echarts', 'packages-plugins/echarts/dist/index.d.ts'],
  ['@docxkit/plugin-invoice', 'packages-plugins/invoice/dist/index.d.ts'],
  ['@docxkit/plugin-letterhead', 'packages-plugins/letterhead/dist/index.d.ts'],
  [
    '@docxkit/plugin-meeting-minutes',
    'packages-plugins/meeting-minutes/dist/index.d.ts',
  ],
  [
    '@docxkit/plugin-page-number',
    'packages-plugins/page-number/dist/index.d.ts',
  ],
  [
    '@docxkit/plugin-property-table',
    'packages-plugins/property-table/dist/index.d.ts',
  ],
  ['@docxkit/plugin-qrcode', 'packages-plugins/qrcode/dist/index.d.ts'],
  [
    '@docxkit/plugin-signature-block',
    'packages-plugins/signature-block/dist/index.d.ts',
  ],
  ['@docxkit/plugin-timeline', 'packages-plugins/timeline/dist/index.d.ts'],
  ['@docxkit/plugin-toc', 'packages-plugins/toc/dist/index.d.ts'],
  ['@docxkit/plugin-watermark', 'packages-plugins/watermark/dist/index.d.ts'],
  ['@docxkit/preset-academic', 'packages-presets/academic/dist/index.d.ts'],
  ['@docxkit/preset-classic', 'packages-presets/classic/dist/index.d.ts'],
  ['@docxkit/preset-modern', 'packages-presets/modern/dist/index.d.ts'],
  ['@docxkit/renderer', 'packages/renderer/dist/index.d.ts'],
  ['@docxkit/theme-minimal', 'packages-themes/minimal/dist/index.d.ts'],
  ['@docxkit/theme-ocean', 'packages-themes/ocean/dist/index.d.ts'],
  ['@docxkit/theme-warm', 'packages-themes/warm/dist/index.d.ts'],
] as const

function collectDeclarationFiles(directory: string): string[] {
  const files: string[] = []

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const entryPath = resolve(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...collectDeclarationFiles(entryPath))
    } else if (entry.name.endsWith('.d.ts')) {
      files.push(entryPath)
    }
  }

  return files.sort()
}

function dependencyRoot(
  packageName: string,
  fromPackage = resolve(ROOT, 'package.json'),
): string {
  const packageRequire = createRequire(fromPackage)
  let currentDirectory = dirname(packageRequire.resolve(packageName))

  while (true) {
    const packageJsonPath = resolve(currentDirectory, 'package.json')
    if (existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as {
        name?: string
      }
      if (packageJson.name === packageName) {
        return currentDirectory
      }
    }

    const parentDirectory = dirname(currentDirectory)
    if (parentDirectory === currentDirectory) {
      throw new Error(
        `[generate-monaco-types] unable to resolve package root: ${packageName}`,
      )
    }
    currentDirectory = parentDirectory
  }
}

function getTypeLibSources(): TypeLibSource[] {
  const sources: TypeLibSource[] = WORKSPACE_MODULES.map(
    ([moduleName, sourcePath]) => ({
      sourcePath: resolve(ROOT, sourcePath),
      virtualPath: toVirtualPath(moduleName),
    }),
  )

  const typesRoot = resolve(ROOT, 'packages/types/dist')
  for (const sourcePath of collectDeclarationFiles(typesRoot)) {
    const declarationPath = relative(typesRoot, sourcePath).split(sep).join('/')
    sources.push({
      sourcePath,
      virtualPath: toVirtualPath('@docxkit/types', declarationPath),
    })
  }

  const docxRoot = dependencyRoot('docx')
  sources.push({
    sourcePath: resolve(docxRoot, 'dist/index.d.ts'),
    virtualPath: toVirtualPath('docx'),
  })

  const echartsRoot = dependencyRoot('echarts')
  sources.push(
    {
      sourcePath: resolve(echartsRoot, 'types/dist/all.d.ts'),
      virtualPath: toVirtualPath('echarts'),
    },
    {
      sourcePath: resolve(echartsRoot, 'types/dist/shared.d.ts'),
      virtualPath: toVirtualPath('echarts', 'shared.d.ts'),
    },
  )

  const rendererPackage = resolve(ROOT, 'packages/renderer/package.json')
  const docxPreviewRoot = dependencyRoot('docx-preview', rendererPackage)
  sources.push({
    sourcePath: resolve(docxPreviewRoot, 'dist/docx-preview.d.ts'),
    virtualPath: toVirtualPath('docx-preview'),
  })

  return sources
}

function main() {
  const sources = getTypeLibSources()
  const seenVirtualPaths = new Set<string>()
  const entries: string[] = []

  for (const source of sources) {
    if (seenVirtualPaths.has(source.virtualPath)) {
      throw new Error(
        `[generate-monaco-types] duplicate virtual path: ${source.virtualPath}`,
      )
    }
    if (!existsSync(source.sourcePath)) {
      throw new Error(
        `[generate-monaco-types] missing declaration: ${source.sourcePath}`,
      )
    }

    seenVirtualPaths.add(source.virtualPath)
    entries.push(
      `  { content: ${JSON.stringify(readFileSync(source.sourcePath, 'utf8'))}, filePath: ${JSON.stringify(source.virtualPath)} },`,
    )
  }

  entries.push(
    `  { content: ${JSON.stringify("declare module 'node:buffer' { export class Buffer extends Uint8Array {} }")}, filePath: 'file:///node_modules/@types/node-buffer/index.d.ts' },`,
  )

  const output = [
    ...HEADER,
    'export const DOCX_KIT_TYPE_LIBS = [',
    ...entries,
    '] as const',
    '',
  ].join('\n')

  writeFileSync(OUTPUT, output, 'utf8')

  console.log(`[generate-monaco-types] wrote ${OUTPUT}`)
  console.log(
    `[generate-monaco-types] ${sources.length + 1} declaration files, ${output.length} bytes`,
  )
}

function toVirtualPath(moduleName: string, declarationPath = 'index.d.ts') {
  return `file:///node_modules/${moduleName}/${declarationPath}`
}

main()
