/**
 * Generate Monaco-friendly type declarations for the playground.
 *
 * Reads the real `.d.ts` files emitted by `tsdown` and produces
 * a TypeScript file that exports `DOCX_KIT_TYPES` — a string constant
 * containing `declare module` blocks that Monaco's TypeScript worker
 * can consume.
 *
 * Strategy:
 *   1. **docx-kit module** — read the umbrella `dist/browser.d.ts`
 *      and all leaf packages, strip `import` lines, and emit a
 *      single `declare module 'docx-kit' { … }` block.
 *      - The umbrella's `declare module '@docxkit/core' { … }`
 *        augmentation is REWRITTEN to target `'docx-kit'` so the
 *        augmentation actually applies to the module playground
 *        users `import` from.
 *      - The `declare` keyword is stripped from declarations
 *        (redundant inside `declare module { … }`).
 *      - A manual `BuiltinPluginMap` augmentation is emitted
 *        with simple type names (no `$1` suffix) so it doesn't
 *        conflict with the umbrella's imports.
 *   2. **docx module** — read `node_modules/docx/dist/index.d.ts`,
 *      strip `import` lines, wrap in `declare module 'docx' { … }`.
 *      - `declare` keyword is also stripped.
 *
 * The resulting blocks are emitted as a regular JS string literal
 * (via `JSON.stringify`) — this avoids all manual escaping pitfalls
 * (backticks, `${…}` interpolation, backslashes in TypeScript
 * template-literal types like `` `#${string}` ``).
 *
 * @example
 *   pnpm tsx scripts/generate-monaco-types.ts
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')

// ─── Configuration ────────────────────────────────────────────────

const UMBRELLA_DTS = 'packages/docx-kit/dist/browser.d.ts'

const DOCXKIT_LEAF_PACKAGES = [
  'packages/core/dist/index.d.ts',
  'packages-plugins/badge/dist/index.d.ts',
  'packages-plugins/barcode/dist/index.d.ts',
  'packages-plugins/callout/dist/index.d.ts',
  'packages-plugins/changelog/dist/index.d.ts',
  'packages-plugins/code-block/dist/index.d.ts',
  'packages-plugins/cover-page/dist/index.d.ts',
  'packages-plugins/data-table/dist/index.d.ts',
  'packages-plugins/divider/dist/index.d.ts',
  'packages-plugins/echarts/dist/index.d.ts',
  'packages-plugins/invoice/dist/index.d.ts',
  'packages-plugins/letterhead/dist/index.d.ts',
  'packages-plugins/meeting-minutes/dist/index.d.ts',
  'packages-plugins/page-number/dist/index.d.ts',
  'packages-plugins/property-table/dist/index.d.ts',
  'packages-plugins/qrcode/dist/index.d.ts',
  'packages-plugins/signature-block/dist/index.d.ts',
  'packages-plugins/timeline/dist/index.d.ts',
  'packages-plugins/toc/dist/index.d.ts',
  'packages-plugins/watermark/dist/index.d.ts',
  'packages-presets/academic/dist/index.d.ts',
  'packages-presets/classic/dist/index.d.ts',
  'packages-presets/modern/dist/index.d.ts',
  'packages-themes/minimal/dist/index.d.ts',
  'packages-themes/ocean/dist/index.d.ts',
  'packages-themes/warm/dist/index.d.ts',
  'packages/loader/dist/index.d.ts',
  'packages/renderer/dist/index.d.ts',
]

const DOCX_DTS = resolve(
  ROOT,
  'node_modules/.pnpm/docx@9.7.1/node_modules/docx/dist/index.d.ts',
)

const OUTPUT = resolve(ROOT, 'docs/.vitepress/utils/monacoTypes.generated.ts')

// ─── Header ───────────────────────────────────────────────────────
const HEADER = [
  '/**',
  ' * AUTO-GENERATED by `scripts/generate-monaco-types.ts` — DO NOT EDIT.',
  ' *',
  ' * Source of truth: the `.d.ts` files listed in',
  ' * `DOCXKIT_LEAF_PACKAGES` (see the generator script).',
  ' *',
  ' * To regenerate, run `pnpm tsx scripts/generate-monaco-types.ts`',
  ' * (also runs automatically as part of `pnpm docs:build`).',
  ' */',
  '',
]

// ─── Helpers ────────────────────────────────────────────────────

/**
 * Rewrite any `declare module '@docxkit/core' { … }` block in `source`
 * so that it targets `'docx-kit'` instead, AND drop it entirely.
 *
 * We drop it because the umbrella's augmentation references the
 * import-alias names like `CalloutOptions$1` which become unresolved
 * once we strip the umbrella's `import` lines.  A cleaner manual
 * augmentation is emitted by `BUILTIN_PLUGIN_MAP_AUGMENTATION`
 * using the plain type names that resolve via the leaf packages.
 */
function dropAugmentationBlock(source: string): string {
  // Match `declare module 'X' { … }` blocks (greedy) and remove them.
  return source.replace(
    /declare\s+module\s+['"][^'"]+['"]\s*\{[\s\S]*?\n\}/g,
    '',
  )
}

/** Indent every non-empty line of `text` by `n` spaces. */
function indent(text: string, n: number): string {
  const pad = ' '.repeat(n)
  return text
    .split('\n')
    .map(line => (line.length === 0 ? line : pad + line))
    .join('\n')
}

/**
 * Strip the `declare` keyword from declarations.
 *
 * When we move declarations from their original `.d.ts` files
 * (where `declare` is necessary) into a `declare module 'X' { … }`
 * block, the `declare` becomes redundant and TS reports
 * "TS1038: A 'declare' modifier cannot be used in an already
 * ambient context."
 *
 * Important: do NOT strip `declare` from `declare module 'X' { … }`
 * opening lines — that would break the augmentation block syntax.
 */
function stripDeclareKeyword(source: string): string {
  // Match `declare` only when NOT followed by `module`.
  return source.replace(/^(\s*)(export\s+)?declare\s+(?!module\b)/gm, '$1$2')
}

/**
 * Strip `import … from "…";` lines, `export { … };` / `export {};` lines,
 * and `export * from "…";` re-exports from a `.d.ts` source.
 *
 * These reference other npm packages and can't be resolved by
 * Monaco's TS worker at runtime.
 */
function stripImportsAndExports(source: string): string {
  return source
    .split('\n')
    .filter(line => {
      const t = line.trim()
      if (t.startsWith('import ')) {
        return false
      }
      if (/^export\s*\{[^}]*\};?\s*$/.test(t)) {
        return false
      }
      if (/^export\s+\*\s+from\s+/.test(t)) {
        return false
      }
      return true
    })
    .join('\n')
}

// ─── BuiltinPluginMap augmentation (manual emission) ────────────

/**
 * Manually emit a `BuiltinPluginMap` augmentation that augments
 * `declare module 'docx-kit' { … }` so the playground gets
 * type-safe `.plugin('callout', { ... })` calls without an
 * explicit `.use()` chain.
 *
 * We use plain plugin option type names (e.g. `CalloutOptions`)
 * which are resolved by the leaf packages' declarations in the
 * same module scope.
 */
const BUILTIN_PLUGIN_MAP_AUGMENTATION = `
interface BuiltinPluginMap {
  badge: BadgeOptions;
  barcode: BarcodeOptions;
  callout: CalloutOptions;
  changelog: ChangelogOptions;
  codeBlock: CodeBlockOptions;
  coverPage: CoverPageOptions;
  dataTable: DataTableOptions;
  divider: DividerOptions;
  echarts: EChartsPluginOptions;
  invoice: InvoiceOptions;
  letterhead: LetterheadOptions;
  meetingMinutes: MeetingMinutesOptions;
  pageNumber: PageNumberOptions;
  propertyTable: PropertyTableOptions;
  qrcode: QRCodePluginOptions;
  signatureBlock: SignatureBlockOptions;
  timeline: TimelineOptions;
  toc: TocOptions;
  watermark: WatermarkOptions;
}
`.trim()

// ─── Main builder functions ────────────────────────────────────

/**
 * Build the `declare module 'docx' { … }` block.
 */
function buildDocxBlock(): string {
  if (!existsSync(DOCX_DTS)) {
    throw new Error(
      `[generate-monaco-types] missing ${DOCX_DTS}\n`
        + 'Run `pnpm install` first.',
    )
  }
  let src = readFileSync(DOCX_DTS, 'utf8')
  src = stripImportsAndExports(src)
  src = stripDeclareKeyword(src)
  return [`declare module 'docx' {`, indent(src, 2), '}'].join('\n')
}

/**
 * Build the body of the `docx-kit` module block by concatenating
 * the umbrella and leaf package declarations, deduped by name.
 *
 * Dedup: a simple regex finds top-level `type` / `interface` /
 * `class` / `function` / `const` / `enum` / `namespace` /
 * `abstract class` / `async function` declaration headers and
 * records their names. A leaf package is skipped entirely if
 * every one of its names is already seen (the umbrella and
 * earlier leaves won the dedup race).
 */
function buildDocxKitBody(): string {
  const seen = new Set<string>()
  const parts: string[] = []

  // Extract declared names from a `.d.ts` source.
  const declNamePattern =
    /^\s*(?:export\s+)?(?:declare\s+)?(?:type|interface|class|function|const|enum|namespace|abstract\s+class|async\s+function)\s+([A-Za-z_$][\w$]*)/gm
  function extractNames(src: string): string[] {
    const names: string[] = []
    let m: RegExpExecArray | null
    while ((m = declNamePattern.exec(src)) !== null) {
      names.push(m[1]!)
    }
    declNamePattern.lastIndex = 0
    return names
  }

  // 1. Umbrella first (so its unique value exports and types win).
  const umbrellaSrc = readLeafDts(UMBRELLA_DTS, { isUmbrella: true })
  if (umbrellaSrc) {
    for (const n of extractNames(umbrellaSrc)) {
      seen.add(n)
    }
    parts.push(umbrellaSrc)
  }

  // 2. Leaf packages.
  for (const relPath of DOCXKIT_LEAF_PACKAGES) {
    const src = readLeafDts(relPath)
    if (!src) {
      continue
    }
    const names = extractNames(src)
    const allSeen = names.length > 0 && names.every(n => seen.has(n))
    if (allSeen) {
      continue
    }
    for (const n of names) {
      seen.add(n)
    }
    parts.push(src)
  }

  // 3. Manual `BuiltinPluginMap` augmentation (uses plain type
  //    names that resolve via the leaf packages in this scope).
  parts.push(BUILTIN_PLUGIN_MAP_AUGMENTATION)

  return parts.join('\n\n')
}

function main() {
  const docxkitBody = buildDocxKitBody()
  const docxBlock = buildDocxBlock()

  const docxkitBlock = [
    `declare module 'docx-kit' {`,
    indent(docxkitBody, 2),
    '}',
  ].join('\n')

  const content = [docxkitBlock, '', docxBlock].join('\n')

  // `JSON.stringify` produces a regular JS string literal with
  // every special character properly escaped (backticks, backslashes,
  // `${…}`, control chars, non-ASCII). This avoids the pitfalls of
  // embedding TS source inside a JS template literal, where:
  //   • `` ` ``  must become `` \` ``
  //   • `\`     must become `\\`
  //   • `${`    must become `\${`
  // When emitted as a plain string, the resulting constant holds the
  // original source verbatim — including valid TS template-literal
  // types like `` `#${string}` ``.
  //
  // We keep the full `JSON.stringify` output (with surrounding `"…"`)
  // and wrap with `unindent(…)` for runtime whitespace normalisation
  // (not for escaping).
  const jsonEncoded = JSON.stringify(content)

  const output = [
    ...HEADER,
    '',
    "import { unindent } from '@ntnyq/utils'",
    '',
    'export const DOCX_KIT_TYPES = unindent(',
    `  ${jsonEncoded}`,
    ')',
    '',
  ].join('\n')

  // ─── Self-check: brace balance must be zero ─────────────────────
  // If unbalanced, Monaco's TS worker will report syntax errors in
  // the `addExtraLib` content.
  let depth = 0
  for (const ch of content) {
    if (ch === '{') {
      depth++
    } else if (ch === '}') {
      depth--
    }
  }
  if (depth !== 0) {
    throw new Error(
      `[generate-monaco-types] brace imbalance detected (depth=${depth}). `
        + 'The generated `declare module` blocks are not properly closed.',
    )
  }

  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, output, 'utf8')

  console.log(`[generate-monaco-types] wrote ${OUTPUT}`)
  console.log(
    `[generate-monaco-types] ${output.length} bytes, ${output.split('\n').length} lines`,
  )
}

// ─── Main ────────────────────────────────────────────────────────

/**
 * Read a `.d.ts` file and return its content with imports/exports
 * stripped, the `declare` keyword removed, and the augmentation
 * target rewritten to `'docx-kit'`.
 *
 * Returns `null` if the file doesn't exist.
 */
function readLeafDts(
  relPath: string,
  opts: { isUmbrella?: boolean } = {},
): string | null {
  const absPath = resolve(ROOT, relPath)
  if (!existsSync(absPath)) {
    console.warn(`[generate-monaco-types] skipping missing ${relPath}`)
    return null
  }
  let src = readFileSync(absPath, 'utf8')
  src = stripImportsAndExports(src)
  if (opts.isUmbrella) {
    src = dropAugmentationBlock(src)
  }
  src = stripDeclareKeyword(src)
  return src
}

main()
